create database vpmsdb;
used vpmsdb;
CREATE TABLE IF NOT EXISTS `vpmsdb`.`tbladmin` (
`ID` INT(11) NOT NULL AUTO_INCREMENT,
`AdminName` VARCHAR(120) NULL DEFAULT NULL,
`UserName` VARCHAR(120) NULL DEFAULT NULL,
`MobileNumber` BIGINT(20) NULL DEFAULT NULL,
`Email` VARCHAR(200) NULL DEFAULT NULL,
`Password` VARCHAR(120) NULL DEFAULT NULL,
`adminregdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1


CREATE TABLE IF NOT EXISTS `vpmsdb`.`tbluser` (
 `id` INT(11) NOT NULL AUTO_INCREMENT,
 `fullname` VARCHAR(100) NULL DEFAULT NULL,
 `mobile` VARCHAR(100) NULL DEFAULT NULL,
 `email` VARCHAR(100) NULL DEFAULT NULL,
 `address` VARCHAR(400) NULL DEFAULT NULL,
 `uname` VARCHAR(45) NULL DEFAULT NULL,
 `password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
 AUTO_INCREMENT = 10
 DEFAULT CHARACTER SET = utf8


CREATE TABLE IF NOT EXISTS `vpmsdb`.`tblcategory` (
`ID` INT(11) NOT NULL AUTO_INCREMENT,
`VehicleCat` VARCHAR(120) NULL DEFAULT NULL,
`CreationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1


CREATE TABLE IF NOT EXISTS `vpmsdb`.`tblparkingseatcapacity` (
`parking_seat` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8


CREATE TABLE IF NOT EXISTS `vpmsdb`.`tblvehicle` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ParkingNumber` VARCHAR(120) NULL DEFAULT NULL,
  `VehicleCategory` VARCHAR(120) NOT NULL,
  `VehicleCompanyname` VARCHAR(120) NULL DEFAULT NULL,
  `RegistrationNumber` VARCHAR(120) NULL DEFAULT NULL,
  `OwnerName` VARCHAR(120) NULL DEFAULT NULL,
  `OwnerContactNumber` BIGINT(20) NULL DEFAULT NULL,
  `InTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `OutTime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `parkingcharge` VARCHAR(120) NULL DEFAULT NULL,
  `remark` MEDIUMTEXT NULL DEFAULT NULL,
  `status` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = latin1